### ISSUE TITLE
using both taocpp/PEGTL and taocpp/json?

### ISSUE THREAD

**Issue by wojdyr** [taocpp/json#13]
I have a project that uses PEGTL and I'll need to read JSON files in this project. So I thought about taocpp/json.
I'm thinking what's the best way to avoid having two copies of PEGTL.
I understand that separate copies may be desirable in some situations, but for me a single version of PEGTL should be sufficient. Currently I keep it in `gemmi/third_party/tao/pegtl*` (gemmi is the name of my project) and I include it with

    #include <tao/pegtl.hpp>

It seems to me that the easiest workaround to have a single version of PEGTL when I add tao/json to `gemmi/third_party` would be to replace #includes and namespaces in my project to:

    #include <tao/json/external/pegtl.hpp>

Although it's not very elegant. Any thoughts?

**Comment by d-frey** [comment]
It was necessary in the past due to parallel development happening and taocpp/json driving some enhancements in taocpp/PEGTL before the latter was released as 2.0.0. Also, we are new to CMake so we first tried to keep things simple.

For the future, I agree that we should change taocpp/json to use either a version of the PEGTL installed in the system (via a package manager) or by pointing taocpp/json to a different directory with the version of the PEGTL to use. I'll try to figure out how to do that properly, if you have any information/experience, please let me know :)

**Comment by wojdyr** [comment]
I don't know what's the most proper way to do it.
For my use case it'd be enough if `json/include/tao/json/external/pegtl*` was moved two levels up.
And then included not as, for example,

    #include "../external/pegtl.hpp"

but as

    #include "../../pegtl.hpp"

**Comment by d-frey** [comment]
That would actually simplify a few things and now that the PEGTL is part of taocpp it fits nicely. I'll look into this idea (probably using git submodule/subtree?), thanks!

**Comment by ColinH** [comment]
We understand the issue, but aren't quite convinced that it's worth changing. The duplicated code isn't a lot. And with all the templates, we don't expect de-duplication to make much difference in the object files. Also, the PEGTL should be seen as an implementation detail of the JSON library that could in theory change at any time. Having separate copies also allows for independent version updates. Our suggestion is to just go ahead and install both libraries. We have also made sure that the PEGTL embedded in the JSON library does not interfere with an additional, separate version used in the same project, see [Embedding the PEGTL](https://github.com/taocpp/PEGTL/blob/master/doc/Installing-and-Using.md#embedding-the-pegtl). If this doesn't work for you, or you have additional questions please feel free to ask here and/or re-open this issue.
