### ISSUE TITLE
looks like `tao::json::value::operator[]` doesn't accept string as a key

### ISSUE THREAD

**Issue by vladimirgamalyan** [taocpp/json#136]
If I understand correctly, the following code should work:

```
int main(int, char**)
{
	const tao::json::value v = {
		{ "foo", 42 }
	};

	std::cout << v["foo"].as<int>() << std::endl;
}
```

But on Windows 11, MSVC 16.11.23 it produces that error message at compile time:

> Error	C2678	binary '[': no operator found which takes a left-hand operand of type 'const tao::json::value' (or there is no acceptable conversion)

**Comment by ColinH** [comment]
Since - independent of whether that original design choice was a good idea or not - we are replicating the behaviour of `std::map` you can't call `operator[]` on a `const tao::json::value` because it might need to insert an object for the given key. The code should compile when you remove the `const`.

**Comment by vladimirgamalyan** [comment]
Oh, seems reasonable. At least there is a method `std::map::at()` for the const case, thank you!

**Comment by ColinH** [comment]
There is also `tao::json::value::at()`, or if you don't want the exception you can use `tao::json::value::find()`.
