### ISSUE TITLE
from_string should support wstring_view

### ISSUE THREAD

**Issue by matbech** [taocpp/json#31]
tao:json::from_string does not support wstring at the moment:
```
std::wstring json_string;
tao::json::from_string(json_string)

```
include\tao\json\from_string.hpp(22): error C2664: 'void tao::json::events::from_string<tao::json::events::to_basic_value<tao::json::traits,tao::json::internal::empty_base>,>(Consumer &,const tao::string_view)': cannot convert argument 2 from 'const std::wstring' to 'const tao::string_view'

Maybe this can be fixed by adding overloads for the other string_view classes in
include\tao\json\events\from_string.hpp
`         void from_string( Consumer& consumer, const tao::string_view data, Ts&&... ts )`

**Comment by d-frey** [comment]
The overloads also need to be implemented, but our parser only supports UTF-8. I don't see any way to support this with reasonable effort. Plus JSON only requires support for UTF-8 anyways... hm...

@Colin Any thoughts on this?

**Comment by matbech** [comment]
As an alternative: given a utf-8 encoded char* input, would it be possible to convert all value strings transparently from utf-8 to wstring?
The use case are Windows applications which for the majority work with wchar_t and not with utf-8 encoded strings.

**Comment by d-frey** [comment]
Storing UTF-16 encoded strings (`wstring` or even `wstring_view`) would be a lot of work, starting with extending `tao::json::type` and adding support for two additional types almost anywhere, extending the events interface and forcing *every* producer and consumer to handle wstrings, then adding comparisons for string vs. wstring as well because they have the same content, just a different representation, ... - no that's not going to happen :)

💡 You could try and specialize the traits (or create your own traits) for `std::wstring`. That would allow you to use `std::wstring` almost seamlessly with our library.

❗️A specialization for `wstring_view` would probably not make much sense as the JSON `value` nodes stores UTF-8 internally, so the conversion would create a temporary and a `wstring_view` would then point to the already-deleted temporary when you return it.

**Comment by Sereglaith** [comment]
It should also be noted that std::wstring (wchar_t) gets compiled as 4 bytes on linux and 2 bytes on windows.
