### ISSUE TITLE
There should be a `basic_value::find(const pointer&)`

### ISSUE THREAD

**Issue by le-migou** [taocpp/json#38]
For consistency. Trying to find a value via a pointer currently requires a try-block.

**Comment by ColinH** [comment]
You mean with a pointer as return value?

Right, it could return `nullptr` when the lookup fails anywhere along the way of resolving the pointer, but we need to be more precise:

- When the lookup fails because a part of the pointer is not found in a container along the way, return `nullptr`.
- When the lookup fails because some Value along the way is not a container of the correct type, should we also return `nullptr`, or throw an exception?
