### ISSUE TITLE
Please consider re-adding empty()

### ISSUE THREAD

**Issue by bobkocisko** [taocpp/json#49]
Hello, I am upgrading from an old version of the library and am disappointed to see that the empty() function has been removed.  I found it helpful and clear to determine whether a document was a container and had anything inside it (without knowing its exact type).  Would you consider re-adding it?  Otherwise I'll need to add my own extension to do the same.

**Comment by bobkocisko** [comment]
It was removed in 4cee8baa59442f702680115a85c42c7646b522c5

**Comment by d-frey** [comment]
We've documented the reason for removing `empty()` and `size()` here: https://github.com/taocpp/json/blob/master/doc/Design-Decisions.md#omitted-functions

There are two ways you can fix the situation.

1. You could write a free function with the desired semantics. This is easy and only requires the public interface. But the calling convention is `empty( v )` instead of `v.empty()`.
2. You could use the [public base facility](https://github.com/taocpp/json/blob/master/doc/Advanced-Use-Cases.md#custom-base-class-for-values) of the traits class to add *your* version of `empty()` and `size()` to the public interface of the values, hence getting back the `v.empty()`.

I added an example (with tests) for the latter option, see https://github.com/taocpp/json/blob/master/src/test/json/public_base.cpp

I hope this solves your problem and explains why we chose to remove `empty()` and `size()` from the out-of-the-box value class.

**Comment by bobkocisko** [comment]
Thank you!
