### ISSUE TITLE
Implement std::visit interface for json values.

### ISSUE THREAD

**Issue by Siapran** [taocpp/json#71]
It would be nice to be able to use visitors on json values like you would with std::visit.
see: https://en.cppreference.com/w/cpp/utility/variant/visit

**Comment by ColinH** [comment]
It seems to be easy, please try with the latest commit - and let's hope that I didn't miss any important reason why it can't always be so easy :-)

**Comment by d-frey** [comment]
Are we sure we want to do it this way? We could also expose the variant with an accessor (getter) and instead of `v.visit( vis );` you'd write `std::visit( vis, v.variant() );`. Benefit: You can have visitors to visit multiple variants at once, the exposed variant can be queried for `.index()`, etc. and you can use other standard methods on it. I guess the real question we need to ask is: How much is `m_variant` an implementation detail or how much do we want to expose it?

(I even considered *deriving* from `std::variant` briefly, but that might have other implications.)

**Comment by Siapran** [comment]
alternatively, specializing or providing the interface needed for std::visit (std::get and index I believe?)

**Comment by d-frey** [comment]
Unfortunately that is not allowed, `std::get` is not a customization point from the standard's point of view. (I would have preferred it, but yeah, not allowed)

**Comment by ColinH** [comment]
@d-frey Yes, how far do we want to expose the variant? I guess at this point there aren't too many reasons to keep it private? We advertise as being standard containers based, we use the standard string classes, so we might as well complete the picture. And then offering a getter could replace `visit()`.

**Comment by ColinH** [comment]
Since it seems to fit with both the design of the library and the code we decided to implement a getter called `basic_value::variant()` instead of `basic_value::visit()`, which is more flexible.
