### ISSUE TITLE
Unable to construct json::value from json::value::object_t

### ISSUE THREAD

**Issue by Siapran** [taocpp/json#72]
This works:
```
return tao::json::to_string([]{
        tao::json::value res;
        res = tao::json::object_t{};
        return res;
    }());
```

This doesn't:
```
return tao::json::to_string(tao::json::value{tao::json::object_t{}});
// alternatively:
return tao::json::to_string(tao::json::object_t{});
```

Edit: fix `object_t{}` typo

**Comment by d-frey** [comment]
* `to_string( value::object{} )` doesn't work because `value::object` is a (static) method, so you'd need round brackets and an (empty) initializer list. Therefore:
* `to_string( value::object({}) )` does work.
* `to_string( value::object_t{} )` does not work because it is just a `std::map<...>`, but `to_string()` want to deduce the `Traits` for `basic_value< Traits >` which does not work either.

I could add an overload for `value::object` so that `to_string( value::object() )` (note: round brackets instead of curly backets) would work.

I don't think that I will try to "fix" the `to_string( value::object_t{} )` as this is not really a reasonable use-case AFAICS. And for the same reason `to_string( tao::json::empty_object )` will not work. To fix both cases I would need to add overloads to `to_string` which will be mostly useless in practice. @ColinH What do you think?

**Comment by Siapran** [comment]
Sorry for the typos, and lack of clarity as to what I'm trying to do.

I have a variable of type `object_t`.
I can assign it to a variable of type `value`.
But I can't construct a `value` from an `object_t`.

How come the assignment operator works, but not the constructor?

**Comment by d-frey** [comment]
You still misunderstand what your problem is. You *can* construct a value from `object_t{}` just fine, if you write `value v( value::object_t{} );` it works as expected.

The problem you have is related to argument deduction and constructing a value on-the-fly. You have a method like

    template< template< typename... > class Traits >
    std::string to_string( const basic_value< Traits >& v ) { ... }

and you pass a non-basic-value, the compiler would need to figure out what `Traits` is - but it can't. You could even have multiple traits defined that would accept, say `object_t{}`. Which one should the compiler choose? (Even with only one traits class available, the compiler simply doesn't know that). Hence an `object_t{}` doesn't work. You'd need a method like

   std::string to_string( const value& v ) { ... }

so that the compiler knows how to do the implicit conversion.

**Comment by Siapran** [comment]
oh. `value{object_t{}}` _does_ work.
I guess I got something mixed up when I tried before... Sorry about that.

And yes, the implicit conversion for to_string makes sense.

**Comment by Siapran** [comment]
actually scratch that, I _am_ getting an error with `auto foo = value{object_t{}};`: [compile output](https://gist.github.com/Siapran/635fd1b5641b6bc36718c72657c851c4)

**Comment by d-frey** [comment]
`object_t` is a member of `basic_value`, so that should be `auto foo = value{ value::object_t{} };`. This also explains your error message `error C2062: type 'unknown-type' unexpected`.

**Comment by d-frey** [comment]
Scratch that, I assume you meant `value{ value::object_t{} };`. But now you've fallen into another trap: "Uniform initialization" simply isn't that uniform as one would hope. In this case

    auto v = value( value::object_t{} ); // round brackets!

would work. But when you use curly brackets, the compiler wants to create a JSON object with the given parameters. But `value::object_t{}` is a single value and there is not key (neither explicitly provided by you nor implicitly for the type `object_t`.). So... this would work:

    auto v = value{ { "key", value::object_t{} } };

**Comment by Siapran** [comment]
I'm using `object_t{}` in my example as a shorthand for an object in my code of type `value::object_t`.

here's an excerpt of the code in question:
```
using jsonValue = tao::json::value;
jsonValue::object_t properties = foo(); // something that returns a jsonValue::object_t
// [...]
auto tmp = jsonValue{properties};
auto str = tao::json::to_string(tmp);
```

**Comment by Siapran** [comment]
oh.

**Comment by d-frey** [comment]
Yeah, the language rules are pretty complicated. To make matters worse: `value{}` does call the default ctor, it does *not* create a JSON object. My advice: Don't use `{}` for initialization, stick with the good, old `()` - *unless* you have an actual reason to use `{}`.

**Comment by Siapran** [comment]
understood. thanks for the help!

**Comment by d-frey** [comment]
You're welcome.
